services:
  api:
    image: tperons/spring-rest-api:${APP_VERSION}
    container_name: spring-rest-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${DB_PORT}/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    networks:
      - database-network
      - proxy-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

networks:
  database-network:
    external: true
  proxy-network:
    external: true
