spring:
  application:
    name: spring-boot-rest-study
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    "[com.tperons]": DEBUG
springdoc:
  paths-to-match: /api/v1/**/**
  swagger-ui:
    use-root-path: true
