CREATE TABLE public.tb_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_name varchar(255) NOT NULL,
	full_name varchar(255) NULL,
	"password" varchar(255) NOT NULL,
	account_non_locked bool NULL,
	credentials_non_expired bool NULL,
	account_non_expired bool NULL,
	enabled bool NULL,
	CONSTRAINT tb_user_pkey PRIMARY KEY (id),
	CONSTRAINT ukdx61ph83p21e9y80scx92i39p UNIQUE (user_name)
);
