CREATE TABLE  public.tb_person (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(32) NOT NULL,
	last_name varchar(32) NOT NULL,
	address varchar(128) NOT NULL,
	gender varchar(16) NOT NULL,
	CONSTRAINT tb_person_pkey PRIMARY KEY (id)
);
